### ISSUE TITLE
Usage of deprecated boolean value for movable

### ISSUE THREAD

**Issue by schokocaylee** [Dataport/polar#145]
**Describe the bug**
In the provided example for the plugin "Pins", `movable` is used with the deprecated boolean value.
https://github.com/Dataport/polar/blob/51280fded2b4d2b92c9a9386a8ebd02eb95bf9d4/pages/examples/address.html#L66

**Expected behavior**
One of the non-deprecated values should be used; e.g.,  ­­`movable: 'drag'`

**Comment by dopenguin** [comment]
Thank you for opening this issue!
We'll address this soon!
