### ISSUE TITLE
mapConfigurations return value

### ISSUE THREAD

**Issue by warm-coolguy** [Dataport/polar#25]
> Correct would be to return `MapConfig` here but that wouldn't immediately work because of the overlap of configuring a plugin during `addPlugins` or during `createMap` via this config.
> 
> An idea would be to have all the completely required parameters, meaning a plugin would not work if not present, to be present during initialization in `addPlugins` and make all configurations in `MapConfig` a `Partial`, so that parameters be be overwritten.
> 
> If you want, you can add that change here. Otherwise, feel free to create an issue and I will tackle that.

_Originally posted by @dopenguin in https://github.com/Dataport/polar/pull/23#discussion_r1397463020_

This issue is about typing issues that occur due to the `mapConfiguration` optionally being defined in multiple places and being merged in a later step. We can't make it all `Partial`, since recursive `Partial` typings do not work with the vuetify types without further ado.

**Comment by warm-coolguy** [comment]
@dopenguin Currently, there's no TSC-detectable issues left with this, since we're just using (partially falsy) initial values for these situation that have to be overwritten later. Seems to be a fine enough solution to me, so I propose we close this issue.

**Comment by dopenguin** [comment]
I agree!
