### ISSUE TITLE
Mobile hover effects

### ISSUE THREAD

**Issue by warm-coolguy** [Dataport/polar#52]
**Situation**

Hovering on the WFS list and pins is not intended on mobile devices, since mobile devices don't *really* support hovering. However, it is *possible* when panning the map with a finger on a pin. It is now up to debate whether to also support "hovering" on the WFS list in the same fashion, which is with touch interactions.

If we plan to support it, the following thread has useful information and links.

https://github.com/Dataport/polar/pull/43#discussion_r1424340939

Beside the above thread, the tooltip displayed for the feature should be removed for mobile, too.

**Resolution**

- Do we want to support "hovering" on mobile devices? ~~Yes~~ / No
- Do we need to remove "hovering" on pins on mobile devices? Yes / ~~No~~

**Comment by dopenguin** [comment]
> [#82 (comment)](https://github.com/Dataport/polar/pull/82#issuecomment-1882537105) Comment open for discussion here. @dopenguin

I'd suggest that we re-evaluate the importance of removing the hovering for mobile devices.  
If it seems important enough, we should make an estimation on how long it would take someone to implement this. If the time needed exceeds the estimation, this would then simply become WONTFIX.

**Comment by dopenguin** [comment]
> > [#82 (comment)](https://github.com/Dataport/polar/pull/82#issuecomment-1882537105) Comment open for discussion here. @dopenguin
> 
> I'd suggest that we re-evaluate the importance of removing the hovering for mobile devices. If it seems important enough, we should make an estimation on how long it would take someone to implement this. If the time needed exceeds the estimation, this would then simply become WONTFIX. @warm-coolguy

After short discussion, we came to the solution to keep this behaviour for now.
