### ISSUE TITLE
GFI feature switcher on mobile device renders only in second feature opening

### ISSUE THREAD

**Issue by warm-coolguy** [Dataport/polar#55]
Refer to https://github.com/Dataport/polar/pull/43#discussion_r1424529113 for details.

**Comment by dopenguin** [comment]
While working on #58, I realized that

```ts
if (this.actionButton !== null) {
  moveHandleProperties.actionButton = this.actionButton
}
```

in the watcher for `windowFeatures` is responsible for adding the ActionButtons of Meldemichel to the Window.

With DISH, the `if`-statement can safely be deleted, as the watcher for `actionButton` triggers the update of the `MoveHandle`
