### ISSUE TITLE
Feature changer after click to feature list sometimes missing

### ISSUE THREAD

**Issue by warm-coolguy** [Dataport/polar#65]
**Describe the bug**
The feature changer in the feature list is sometimes missing, effectively only making available to further inspection the first clicked item.

**Expected behavior**
If a marker with multiple features is selected, users can toggle between the markers with forward/backward buttons.

**Steps to reproduce**
1. Open feature list in Meldemichel client
2. Click on a feature from a multimarker on a non-max-zoom level.
3. The feature is displayed in the window, but the user can't change to other features of the same multimarker.

**Comment by dopenguin** [comment]
The problem arises as only a singular feature without cluster information is further processed when clicking the feature in the list.

@warm-coolguy and I decided on the following solution:

- The above behaviour is implemented
- When clicking on a single feature in the map and then zooming out sometimes a cluster is created. The now clustered features can be selected in the gfi via the feature changer
- The reverse situation from above (having said cluster and zooming in) leads to less selectable features via the feature changer
- When changing between features, the map centers on the respective feature
